/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropdownSelect: typeof import('./components/DropdownSelect.vue')['default']
    FileBrowser: typeof import('./components/FileBrowser.vue')['default']
    LucideAlertCircle: typeof import('@lucide/vue')['AlertCircle']
    LucideArrowRight: typeof import('@lucide/vue')['ArrowRight']
    LucideArrowUpDown: typeof import('@lucide/vue')['ArrowUpDown']
    LucideCheck: typeof import('@lucide/vue')['Check']
    LucideChevronDown: typeof import('@lucide/vue')['ChevronDown']
    LucideChevronRight: typeof import('@lucide/vue')['ChevronRight']
    LucideCircleX: typeof import('@lucide/vue')['CircleX']
    LucideCopy: typeof import('@lucide/vue')['Copy']
    LucideDownload: typeof import('@lucide/vue')['Download']
    LucideFile: typeof import('@lucide/vue')['File']
    LucideFileJson: typeof import('@lucide/vue')['FileJson']
    LucideFiles: typeof import('@lucide/vue')['Files']
    LucideFileVideo: typeof import('@lucide/vue')['FileVideo']
    LucideFolder: typeof import('@lucide/vue')['Folder']
    LucideHardDrive: typeof import('@lucide/vue')['HardDrive']
    LucideHash: typeof import('@lucide/vue')['Hash']
    LucideLayers: typeof import('@lucide/vue')['Layers']
    LucideLoader2: typeof import('@lucide/vue')['Loader2']
    LucideLoaderCircle: typeof import('@lucide/vue')['LoaderCircle']
    LucideMoon: typeof import('@lucide/vue')['Moon']
    LucideMousePointer2: typeof import('@lucide/vue')['MousePointer2']
    LucideMusic: typeof import('@lucide/vue')['Music']
    LucidePackage: typeof import('@lucide/vue')['Package']
    LucidePackageOpen: typeof import('@lucide/vue')['PackageOpen']
    LucidePackageX: typeof import('@lucide/vue')['PackageX']
    LucidePlus: typeof import('@lucide/vue')['Plus']
    LucideRefreshCw: typeof import('@lucide/vue')['RefreshCw']
    LucideSearch: typeof import('@lucide/vue')['Search']
    LucideSettings: typeof import('@lucide/vue')['Settings']
    LucideSun: typeof import('@lucide/vue')['Sun']
    LucideTag: typeof import('@lucide/vue')['Tag']
    LucideTrash2: typeof import('@lucide/vue')['Trash2']
    LucideTriangleAlert: typeof import('@lucide/vue')['TriangleAlert']
    LucideUser: typeof import('@lucide/vue')['User']
    LucideX: typeof import('@lucide/vue')['X']
    NavBar: typeof import('./components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideGameList: typeof import('./components/layout/SideGameList.vue')['default']
    SidePageList: typeof import('./components/layout/SidePageList.vue')['default']
    TagBadge: typeof import('./components/TagBadge.vue')['default']
  }
}
